import Head from 'next/head'
import Image from 'next/image';
import sendSVG from '../public/assets/send.svg';
import {handleSubmit} from '../utils/gpt-script';
import {useEffect} from 'react';


export default function Home() {
    useEffect(() => {
        const listener = (event: KeyboardEvent) => {
            if (event.key === 'Enter' || event.code === 'NumpadEnter') {
                console.log('Enter key was pressed. Running your function...');
                handleSubmit(event);
            }
        };
        document.addEventListener('keydown', listener);
        return () => {
            document.removeEventListener('keydown', listener);
        };
    }, []);

    return (
        <>
            <Head>
                <title>Responsive AI</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.png"/>
            </Head>
            <div className="app">
                <div className="chat_container"></div>
                <div className="input_container">
                    <form className="form" onSubmit={handleSubmit}>
                        <textarea name="prompt" cols={1} rows={1} placeholder="Ask Codex..."></textarea>
                        <button type="submit"><Image src={sendSVG} alt="send" width={500} height={500}/>
                        </button>
                    </form>
                </div>
            </div>
        </>
    )
}